save_dir: "/home/triniborrell/home/projects/TOTEM_for_EEG_code/save/"
gpu_id: 0
data_init_cpu_or_gpu: "cpu"
vqvae_config: 
  general_seed: 47
  model_name: "vqvae"
  model_save_name: "vqvae_eeg_test"
  data_name: "autoformer_vqvae"
  pretrained: false
  learning_rate: 0.001
  num_epochs: 200
  batch_size: 4096
  block_hidden_size: 128
  num_residual_layers: 2
  res_hidden_size: 64
  embedding_dim: 64
  num_embeddings: 256
  commitment_cost: 0.25
  compression_factor: 4
  dataset: "a_dataset.csv" 
  dataset_base_path: "/home/triniborrell/home/projects/TOTEM_for_EEG_code/data/"
  